
# SAS Basics

# DATA Step

## Missing Value

SAS uses `.` to represent missing value for numeric variable and a space `" "` to represent missing value for character variable. In data step or other condition statement, we may want to determine whether a value is missing or not. For numerical type value, use `val=.` to check missing value. For character type value, use 'val=" "' to check missing. If you don't know the type of the data yet, use the function, `missing(val)` to check.

## Input from Raw Typed Data

For unaligned space-delimited raw data, simply use the following code example 

    data output;
      input numvar1 strvar $ numvar2;
      datalines;
    1 hello 1.2
    2 yes 1.5
    3 good 2.5
    run;

If the delimiter is a comma, add a `infile` statement line with `dlm` option

    data output;
      infile datalines dlm=',';
      input numvar1 strvar $ numvar2;
    datalines;
    1,hello ,1.2
    2,yes ,1.5
    3,good ,2.5
    run;

## Input from SAS Data

Use `set` to read input data and generate new outputs

    data output;
      set input;
    run;

## Subset Data by Secifying Row

If you know which index range you want to subset, use `firstobs` (beginning position) and `obs` (how many observations to read) options under `set` to subset your data

	data output;
	  set input(firstobs=12, obs=10)
	run;

## Subset Data by Conditioning Row

If you want to select rows satisfying given condition, use the `where` statement in the data step.

    data output;
    set input;
    where (var1)>5 and length(var2)>=10;
    run;

You may use >, >=, <, <=, =, ~=, and, or logical operators.

## Select Variables

You may extract given variables or drop certain variables or rename variables with three different methods

`keep/drop` statements. It selects the variables at the middle stage of data step, applying to all output datasets.

    data output;
      set input;
      keep=var1 var2;
    run;
    data output;
      set input;
      drop=var3 var4;
    run;
    data output;
      set input;
      rename var1=newvar1 var2=newvar2;
    run;

`keep/drop` options in the `set` statement. It selects the variables at the the very beginning stage of reading input buffer.

    data output;
      set input( keep=var1 var2 );
    run;
    data output;
      set input( drop=var3 var4 );
    run;
    data output;
      set input( rename=(var1=newvar1 var2=newvar2) );
    run;

`keep/drop` options in `data` statement. It selects the variables at the final stage of data step.

    data output( keep=var1 var2 );
      set input;
    run;
    data output( drop=var3 var4 );
      set input;
    run;
    data output( rename=(var1=newvar1 var2=newvar2) );
      set input;
    run;

The choice of these may change the behavior and efficiency in each stage of data step.

## DATA Functions

Function can be applied in real time to variables in data step. Here we use some notations to represent input in differenty data type.

* `in_str` string
* `i j k`

Some useful functions are

* `||` is used to connect multiple string constant and string variable. For example, `var1||var2||'haha'`.
* `trim( in_str)` removes trailing blanks. If input is pure multiple blanks, output is one `" "` blank.
* `trimn( in_str)` removes trailing blanks. If input is pure multiple blanks, output has zero blank.
* `compress( in_str)` removes all blanks in the string variable.
* `length( in_str)` 
* `substr( in_str, begpos, n)`
* `compress( in_str)`
* `scan( in_str, i_word, '.')`

## Reorder Variables

Sometimes, we want to rearrange the order of columns (variables) in the SAS dataset. One simple way to do it is to use `format` statement in the data step

    data output;
      format var5 var4 var3 var2 var1;
      set input;
    run;

Remember that, `format` statement should be before `set` statement for the reorder to work.

# Graphics

`sgplot`

	proc sgplot data=input;
	  dot category_var ;
	  hbar category_var ;
	  vbar category_var ;
	  
	run;

# Macro Programming

Comparison Operators

`=` `EQ` | `^=` `~=` `<>` `NE` | `>` `GT` | `<` `LT` | `>=` `GE` | `<=` `LE`

`&` `AND`

`|` `OR`

`^` `~` `NOT`

# SQL Procedure


## Comparison Operators

`=` `EQ` | `^=` `~=` `<>` `NE` | `>` `GT` | `<` `LT` | `>=` `GE` | `<=` `LE`

`&` `AND`

`|` `OR`

`^` `~` `NOT`

`ANY`

`ALL`

`BETWEEN . AND .` check between

`CONTAINS` check containing

`EXSITS` check existing

`IN` check inclusion. For example, `where val in (1, 2, 3)`

`NOT IN` check exclusion. For example, `where val in ("a", '2', 'c')`

`IS NULL` | `IS MISSING` check missing

`IS NOT NULL` | `IS NOT MISSING` check existing

`LIKE` pattern match

`=*` sounds like